### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gorlapraveen** [gorlapraveen/firefox_b2b_comm_radio_addon#6]
# Roadmap
---------------------------------------------------------------------------------------------------------------------------------------------------------
**Firefox Browser to Browser Radio communication for Internet Access**

The goal of this project is to ease  individual Internet access and circumventing Individual censorship while working with open communities.

## What things do we need to do?
-------------------------------------------------------------------------------------------------------------------------
We need to gather resources( #4  , #2  , #3 ), helping hands(community contributors)  and roadmap( #6 ) .

Please checkout our [contribution profile](https://github.com/gorlapraveen/firefox_b2b_comm_radio_addon#contributors-profile), [Project Boards](https://github.com/gorlapraveen/firefox_b2b_comm_radio_addon/projects/1) and [README]( https://github.com/gorlapraveen/firefox_b2b_comm_radio_addon#firefox-browser-to-browser-radio-communication-for-internet-access--radio--addon)

## Milestones:

- [x]  Addon  flexibility for interacting with Hardware Modules. 
  - [x]  Lookup existing addon framework working procedure. 
  - [x] Implementing Basic sample !  
- [x]  GNU Radio framework.  
  - [x] GNU radio Resources Gathering.  
 -  [x] GNU radio mac based ping from two stations : Includes two GNU radio SDR hardware  Modules.
  - [ ] GNU radio TCP/IP ping from two stations : Includes two GNU radio SDR hardware  Modules.
- [x] Configuring the Interaction between Browser Addon  and GNU radio. 
  - [ ] Scripts for Addon and Hardware module communication. 
  - [x] Scripts for  Hardware module communication. 
  - [x]   Success or fail test implementation  : If succeed move to next step else, repeat the sectional procedure.
- [ ] Testing .
  - [x] Real-Time testing for alpha with 1-4 members. : If satisfied move to  next step else, move to previous section.
  - [ ] Real Time testing for beta with 1-10 members. : With Feedback: If satisfied move to  next step else, move to previous section.
- [ ] Stable release use. 
   - [ ] Real-Time use with >10 members : With Feedback: If satisfied move for stable release else, move to previous section.

------------------------------------------------------------------------------------------------------------------------------------------------------

This issue( #6 ) is updated when and when needed. Issue contributors @gorlapraveen @rajasekharponakala @tejasri19 and @katjaq

**Comment by katjaq** [comment]
Fantastic! This is a very nice structure that will help you lead and realize your project. 
Try to add dates by when you would like these milestones to be completed – this will train you in estimating your work load and time needed, and it will also help you keep on track with your project. This can also help drum up interest of potential testers for your alpha release, since users would know when to come and look for a first version :), and it also reassures them that you are currently working on this project.
Great job!

**Comment by gorlapraveen** [comment]
> Fantastic! This is a very nice structure that will help you lead and realize your project.
> Try to add dates by when you would like these milestones to be completed – this will train you in estimating your work load and time needed, and it will also help you keep on track with your project. This can also help drum up interest of potential testers for your alpha release, since users would know when to come and look for a first version :), and it also reassures them that you are currently working on this project.
> Great job!

Sure, We will get in with that!
